/**
 * Tag database: one `-listx -f` run, parsed into a catalog used by the
 * argument builder's whitelist and (in a later leaf) the autocomplete
 * endpoint. The catalog is cached on disk under app/data/ (gitignored) so
 * startup stays fast; the cache is keyed by engine version.
 *
 * The 13.59 `-listx -f` XML is machine-generated and regular:
 *
 *   <table name='IPTC::Main' g0='IPTC' g1='IPTC' g2='Image'>
 *    <tag id='Keywords' name='Keywords' type='string' count='64'
 *         writable='true' flags='List'>
 *     <desc lang='en'>Keywords</desc>
 *    ...
 *
 * Attribute values are single-quoted; `flags` is comma-separated. A tiny
 * purpose-built scanner is used instead of pulling in an XML dependency —
 * the input shape is pinned to the vendored engine and the parser fails
 * loudly if the shape ever changes.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { TagCatalog, TagInfo } from '@metadesk/shared';
import { runOnce } from './exiftoolSession.js';

export interface LoadTagCatalogOptions {
  executablePath: string;
  /** Cache directory. Defaults to <app>/data. */
  cacheDir?: string;
  /** Skip reading/writing the on-disk cache. */
  useCache?: boolean;
  timeoutMs?: number;
}

export interface TagCatalogLoadResult {
  catalog: TagCatalog;
  /** Absolute cache file path, or null when caching was disabled. */
  cachePath: string | null;
  fromCache: boolean;
  /** XML byte length, for diagnostics. */
  xmlBytes: number;
  durationMs: number;
}

/** Default cache dir: <app>/data (the app root is three levels up from here). */
export function defaultCacheDir(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  return path.resolve(here, '../../../data');
}

export function cachePathFor(cacheDir: string, version: string): string {
  return path.join(cacheDir, `tag-catalog-${version}.json`);
}

/** Fetch and parse the catalog, using (and refreshing) the on-disk cache. */
export async function loadTagCatalog(opts: LoadTagCatalogOptions): Promise<TagCatalogLoadResult> {
  const startedAt = Date.now();
  const useCache = opts.useCache ?? true;
  const cacheDir = opts.cacheDir ?? defaultCacheDir();

  if (useCache) {
    await mkdir(cacheDir, { recursive: true });
    // Try the newest cache file present; the engine version is discovered
    // from the file itself, so a stale-but-valid cache still loads.
    const cached = await readNewestCache(cacheDir);
    if (cached !== null) {
      return {
        catalog: cached.catalog,
        cachePath: cached.path,
        fromCache: true,
        xmlBytes: 0,
        durationMs: Date.now() - startedAt,
      };
    }
  }

  const listing = await runOnce(opts.executablePath, ['-listx', '-f'], {
    timeoutMs: opts.timeoutMs ?? 120_000,
  });
  const versionMatch = /<!--\s*Generated by Image::ExifTool (\d+\.\d+)\s*-->/.exec(listing.stdout);
  const version = versionMatch?.[1] ?? 'unknown';
  const catalog = parseListxXml(listing.stdout, version);

  let writtenPath: string | null = null;
  if (useCache) {
    writtenPath = cachePathFor(cacheDir, version);
    await writeFile(writtenPath, JSON.stringify(catalog), 'utf8');
  }

  return {
    catalog,
    cachePath: writtenPath,
    fromCache: false,
    xmlBytes: Buffer.byteLength(listing.stdout, 'utf8'),
    durationMs: Date.now() - startedAt,
  };
}

async function readNewestCache(
  cacheDir: string,
): Promise<{ catalog: TagCatalog; path: string } | null> {
  const { readdir, readFile: readFileFn } = await import('node:fs/promises');
  let names: string[];
  try {
    names = await readdir(cacheDir);
  } catch {
    return null;
  }
  const candidates = names
    .filter((n) => /^tag-catalog-\d+\.\d+\.json$/.test(n))
    .sort()
    .reverse();
  for (const name of candidates) {
    const full = path.join(cacheDir, name);
    try {
      const raw = await readFileFn(full, 'utf8');
      const parsed = JSON.parse(raw) as TagCatalog;
      if (
        typeof parsed.exiftoolVersion === 'string' &&
        parsed.tags !== null &&
        typeof parsed.tags === 'object'
      ) {
        return { catalog: parsed, path: full };
      }
    } catch {
      /* corrupt cache file: fall through and rebuild */
    }
  }
  return null;
}

/**
 * Parse `-listx -f` XML into a {@link TagCatalog}.
 *
 * `tags` is keyed by lowercase `family1:TagName`; `nameIndex` maps a lowercase
 * bare tag name to every key that carries it, so lookups work with or without
 * a group prefix.
 */
export function parseListxXml(xml: string, exiftoolVersion: string): TagCatalog {
  if (!xml.includes('<taginfo>')) {
    throw new Error('parseListxXml: input does not look like exiftool -listx output');
  }

  const tags: Record<string, TagInfo> = {};
  const nameIndex: Record<string, string[]> = {};

  const tableRe = /<table\s+([^>]*?)>/g;
  let tableMatch: RegExpExecArray | null;

  while ((tableMatch = tableRe.exec(xml)) !== null) {
    const tableAttrs = parseAttrs(tableMatch[1] ?? '');
    const tableStart = tableMatch.index + tableMatch[0].length;
    const tableEnd = xml.indexOf('</table>', tableStart);
    if (tableEnd < 0) break;
    const body = xml.slice(tableStart, tableEnd);

    const tagRe = /<tag\s+([^>]*?)>/g;
    let tagMatch: RegExpExecArray | null;
    while ((tagMatch = tagRe.exec(body)) !== null) {
      const attrs = parseAttrs(tagMatch[1] ?? '');
      const name = attrs.get('name');
      if (name === undefined || name.length === 0) continue;

      const elementStart = tagMatch.index + tagMatch[0].length;
      const elementEnd = body.indexOf('</tag>', elementStart);
      const element =
        elementEnd < 0 ? '' : body.slice(elementStart, elementEnd);
      const description = /<desc lang='en'>([\s\S]*?)<\/desc>/.exec(element)?.[1];

      const groups: Record<string, string> = {};
      for (const [key, value] of tableAttrs) {
        if (/^g[0-9]$/.test(key)) groups[key.slice(1)] = value;
      }
      for (const [key, value] of attrs) {
        if (/^g[0-9]$/.test(key)) groups[key.slice(1)] = value;
      }

      const flagString = attrs.get('flags') ?? '';
      const flagSet = new Set(
        flagString
          .split(',')
          .map((f) => f.trim())
          .filter((f) => f.length > 0),
      );

      const info: TagInfo = {
        name,
        groups,
        writable: attrs.get('writable') === 'true',
        protected: flagSet.has('Protected'),
        list: flagSet.has('List'),
        binary: flagSet.has('Binary'),
        mandatory: flagSet.has('Mandatory'),
        permanent: flagSet.has('Permanent'),
        unsafe: flagSet.has('Unsafe'),
        avoid: flagSet.has('Avoid'),
        description: description?.trim(),
        notes: flagString.length > 0 ? flagString : undefined,
      };

      const family1 = groups['1'] ?? groups['0'] ?? 'Other';
      const key = `${family1.toLowerCase()}:${name.toLowerCase()}`;
      // First definition wins: the primary table for a tag is emitted first.
      if (tags[key] === undefined) {
        tags[key] = info;
        const bare = name.toLowerCase();
        const bucket = nameIndex[bare];
        if (bucket === undefined) nameIndex[bare] = [key];
        else if (!bucket.includes(key)) bucket.push(key);
      }
    }
  }

  const total = Object.keys(tags).length;
  if (total < 1000) {
    throw new Error(
      `parseListxXml: implausibly few tags parsed (${total}); the -listx XML shape has changed`,
    );
  }

  return {
    exiftoolVersion,
    builtAt: new Date().toISOString(),
    tags,
    nameIndex,
  };
}

/** Attribute scanner for single-quoted XML attributes. */
function parseAttrs(fragment: string): Map<string, string> {
  const attrs = new Map<string, string>();
  const re = /([A-Za-z0-9_]+)='([^']*)'/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(fragment)) !== null) {
    attrs.set(m[1] ?? '', m[2] ?? '');
  }
  return attrs;
}

/**
 * Look up a tag by a user-spelled name, with or without a group prefix.
 * Returns the canonical catalog entry plus the group-qualified key.
 */
export function lookupTag(
  catalog: TagCatalog,
  tagWithOptionalGroup: string,
): { key: string; info: TagInfo } | null {
  const cleaned = tagWithOptionalGroup.trim();
  if (cleaned.length === 0) return null;

  if (cleaned.includes(':')) {
    const parts = cleaned.split(':').filter((p) => p.length > 0);
    if (parts.length === 0) return null;
    const bare = (parts[parts.length - 1] ?? '').toLowerCase();
    // Any group prefix in the string may be a family-0 or family-1 name; try
    // every family-1 candidate first, then fall back to a bare-name match.
    const candidates = parts.map((p) => p.toLowerCase());
    for (const group of candidates) {
      const key = `${group}:${bare}`;
      const direct = catalog.tags[key];
      if (direct !== undefined) return { key, info: direct };
    }
  }

  const bare = cleaned.split(':').pop()?.toLowerCase() ?? '';
  const keys = catalog.nameIndex[bare];
  if (keys === undefined || keys.length === 0) return null;
  const key = keys[0];
  if (key === undefined) return null;
  const info = catalog.tags[key];
  return info === undefined ? null : { key, info };
}
